{
 "title": "Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Workers RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sim_worker_pass[$__interval])"
    }
   ]
  },
  {
   "title": "Working vs Online Workers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(sim_workers_working)", "legendFormat": "Working" },
    { "expr": "sum(sim_workers_online)", "legendFormat": "Online" }
   ]
  },
  {
   "title": "Worker Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sim_workers_utilized)/sum(sim_workers_online)",
     "legendFormat": "Utilization"
    }
   ]
  },
  {
   "title": "Request Time (milliseconds)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sim_request_queueing_time{quantile=\"0.9\"}",
     "legendFormat": "P90 Queueing Time"
    },
    {
     "expr": "avg(sim_request_processing_time)",
     "legendFormat": "Processing Time"
    }
   ]
  },
  {
   "title": "Number of Accepted Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(sim_request_edge_passed[$__interval]) ",
     "legendFormat": "Accepted Requests (pod: {{shop_id}})"
    }
   ]
  },
  {
   "title": "Number of Rejected Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(sim_request_edge_dropped[$__interval])",
     "legendFormat": "Rejected Request (pod: {{shop_id}})"
    }
   ]
  },
  {
   "title": "Number of Dropped Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(sim_request_edge_dropped[$__interval])"
    }
   ]
  },
  {
   "title": "Controller Measured Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sim_measured_load" }
   ]
  }
 ]
}